---
- hosts: keycloak
  vars:
    my_keycloak_version: '6.0.1'
    keycloak_archive_on_target: true
    # 2.2.3, 2.4.0 and 2.4.1 seemed not to work with Keycloak, in my tests.
    # This person had success with 2.2.2: https://yoshinorin.net/2018/03/21/keycloak-with-mariadb/
    wildfly_mariadb_connector_j_version: '2.2.2'
    mariadb_custom_cnf:
      mysqld:
        general-log:
        general-log-file: queries.log
        log-output: file

  roles:
    - {
       role: nkinder.keycloak,
       keycloak_version: "{{ my_keycloak_version }}",
       keycloak_admin_password: "password"
    }
    - {
      role: bertvv.mariadb,
      become: true,
      mariadb_bind_address: '0.0.0.0',
      mariadb_root_password: 'root',
      mariadb_databases: [{name: 'keycloak_db'}],
      mariadb_users: [
        {
          name: keycloak,
          password: keycloak,
          priv: "keycloak_db.*:ALL,GRANT",
          host: "127.0.0.1",
        }
      ]
    }
    - {
      role: ansible-wildfly-mariadb-connector-j,
      become: true,
      wildfly_mariadb_connector_j_path: '/opt/keycloak/keycloak-{{ my_keycloak_version }}/modules/system/layers/keycloak/org/mariadb/jdbc/main/',
      wildfly_mariadb_connector_j_clean_old_files: true
    }

  pre_tasks:
  - name: Set hosts file
    copy: src=hosts dest=/etc/hosts owner=root group=root
    become: true

  tasks:
  # Probably not really needed, keycloak shouldn't write there. The files themselves
  # are left as owned by root, since everyone else can read them.
  - name: Ensure owner and permissions of MariaDB Connector/J
    file:
      owner: keycloak
      group: keycloak
      path: "{{ item }}"
    become: true
    loop:
    - "/opt/keycloak/keycloak-{{ my_keycloak_version }}/modules/system/layers/keycloak/org" # This one should already exist
    - "/opt/keycloak/keycloak-{{ my_keycloak_version }}/modules/system/layers/keycloak/org/mariadb"
    - "/opt/keycloak/keycloak-{{ my_keycloak_version }}/modules/system/layers/keycloak/org/mariadb/jdbc"
    - "/opt/keycloak/keycloak-{{ my_keycloak_version }}/modules/system/layers/keycloak/org/mariadb/jdbc/main"

  # With certificates from a trusted CA this will not be needed...
  - name: Copy LDAP self-signed certificates
    copy:
      src: "ca/{{ item }}"
      dest: "/opt/keycloak/keycloak-{{ my_keycloak_version }}/{{ item }}"
      mode: '444'
      seuser: unconfined_u
      setype: cert_t
      owner: root
      group: root
    become: true
    loop:
    - ldap1_example_local_cert.pem
    - ldap2_example_local_cert.pem

  - name: Add certificates to keystore
    java_cert:
      cert_alias: "{{ item[:-4] }}"
      cert_path: "/opt/keycloak/keycloak-{{ my_keycloak_version }}/{{ item }}"
      keystore_path: "/opt/keycloak/keycloak-{{ my_keycloak_version }}/standalone/configuration/ldap.jks"
      keystore_pass: "password"
      keystore_create: yes
      state: present
    become: true
    register: keystore_result
    loop:
    - ldap1_example_local_cert.pem
    - ldap2_example_local_cert.pem

  - name: Copy standalone.xml
    template:
      src: "keycloak/standalone.xml"
      dest: "/opt/keycloak/keycloak-{{ my_keycloak_version }}/standalone/configuration/standalone.xml"
      owner: root
      group: root
      mode: 0644
    become: true
    register: standalone_xml_result

  #- name: Create cli script to import certificates
    #copy:
      #content: |
        #/subsystem=keycloak-server/spi=truststore:add()
        #/subsystem=keycloak-server/spi=truststore/provider=file:add(enabled=true)
        #/subsystem=keycloak-server/spi=truststore/provider=file:write-attribute(name=properties, value={"file"="/opt/keycloak/keycloak-{{ my_keycloak_version }}/standalone/configuration/ldap.jks","password"="password","hostname-verification-policy"="WILDCARD","disabled"="false"}
      #dest: "/opt/keycloak/keycloak-{{ my_keycloak_version }}/standalone/configuration/ldap.cli"
      #owner: root
      #group: root
      #mode: 0400
    #become: true

  #- name: Apply certificates configuration
    #command:
    #args:
      #argv:
        #- "/opt/keycloak/keycloak-{{ my_keycloak_version }}/bin/jboss-cli.sh"
        #- "--connect"
        #- "--timeout=30000"
        #- "--file=/opt/keycloak/keycloak-{{ my_keycloak_version }}/standalone/configuration/ldap.cli"
    #become: true

  - name: restart keycloak
    systemd:
      name: keycloak
      state: restarted
    become: yes
    when: wildfly_mariadb_connector_j_changed.changed or keystore_result.changed or standalone_xml_result.changed

  # Switching to MariaDB = the embedded H2 database is lost, and all users are gone with it.
  - name: create Keycloak admin user, again
    command: "/opt/keycloak/keycloak-{{ my_keycloak_version }}/bin/add-user-keycloak.sh -r master -u admin -p password"
    become: yes
    when: wildfly_mariadb_connector_j_changed.changed or keystore_result.changed or standalone_xml_result.changed
