---
- hosts: ldap2
  become: true

  vars:
    dirsrv_suffix: "dc=sso,dc=local"
    dirsrv_rootdn_password: secret2
    dirsrv_tls_certificate_trusted: false
    other_cert: "ca/ldap1_sso_local_cert.pem"

  pre_tasks:
  - name: Set hosts file
    copy: src=hosts dest=/etc/hosts owner=root group=root

  roles:
    -
      role: 389ds-server
      dirsrv_install_examples: false
      dirsrv_tls_enabled: true
      # ./cert.sh ldap2.sso.local
      dirsrv_tls_cert_file: "ca/ldap2_sso_local_cert.pem"
      dirsrv_tls_key_file: "ca/ldap2_sso_local.key"
      dirsrv_tls_files_remote: false
      dirsrv_tls_enforced: false
      dirsrv_password_storage_scheme: "PBKDF2_SHA256"
      dirsrv_plugins_enabled:
        MemberOf Plugin: true
      dirsrv_custom_schema:
      - "schema/97schac.ldif"
      - "schema/98ssh.ldif"
      - "schema/98telegram.ldif"
      - "schema/98weeeopen.ldif"
    -
      role: 389ds-replication
      dirsrv_replica_role: 'both'
      dirsrv_uri: "ldap://localhost"
      dirsrv_use_starttls: true
      dirsrv_replication_user_password: "icauvaelae3reixeiP9ahgh0ei"
      dirsrv_replication_user_password_remote: "Sahj0aedolo0aiNgusoo8onu0s" # On the other server
      dirsrv_consumer_uri: "ldap://ldap1.sso.local:389/" # The other server
      dirsrv_supplier_replica_id: 2

  tasks:
  - block:
    - name: Copy other cert
      copy:
        src: "{{ other_cert }}"
        dest: "/tmp/other-cert-ansible-managed.crt"
        mode: '400'
        setype: cert_t
      changed_when: false

    - name: Install other certificate into NSS db
      command: >
        certutil -A
        -d '/etc/dirsrv/slapd-default'
        -n '{{ other_cert | basename | replace('.', '_') }}-ansible-managed'
        -t 'PC,PC,PC'
        -i '/tmp/other-cert-ansible-managed.crt'
      changed_when: false

    - name: Restart 389DS
      service:
        name: "dirsrv@{{ dirsrv_serverid }}"
        state: restarted

    always:
    - name: Remove temporary files
      file:
        state: absent
        path: "/tmp/other-cert-ansible-managed.crt"
      changed_when: false

  - name: Apply policies
    include: policies.yml
