---
- hosts: mm1
  become: true

  vars:
    dirsrv_suffix: "dc=example,dc=local"
    dirsrv_rootdn_password: secret1
    other_cert: "ca/ldap2_example_local_cert.pem"
    dirsrv_tls_certificate_trusted: false

  pre_tasks:
  - name: Set hosts file
    copy: src=hosts dest=/etc/hosts owner=root group=root

  roles:
    -
      role: 389ds-server
      dirsrv_install_examples: false
      dirsrv_tls_enabled: true
      # ./cert.sh ldap1.sso.local
      dirsrv_tls_cert_file: "ca/ldap1_example_local_cert.pem"
      dirsrv_tls_key_file: "ca/ldap1_example_local.key"
      dirsrv_tls_files_remote: false
      dirsrv_tls_enforced: false
      dirsrv_password_storage_scheme: "PBKDF2_SHA256"
      dirsrv_plugins_enabled:
        MemberOf Plugin: true
      dirsrv_custom_schema:
      - "schema/97schac.ldif"
      - "schema/98ssh.ldif"
      - "schema/98telegram.ldif"
      - "schema/98weeeopen.ldif"
    -
      role: 389ds-replication
      dirsrv_replica_role: 'both'
      dirsrv_uri: "ldap://localhost"
      dirsrv_use_starttls: true
      dirsrv_replication_user_password: "Sahj0aedolo0aiNgusoo8onu0s"
      dirsrv_replication_user_password_remote: "icauvaelae3reixeiP9ahgh0ei" # On the other server
      dirsrv_consumer_uri: "ldap://ldap2.sso.local:389/" # The other server
      dirsrv_supplier_replica_id: 1

  tasks:
  - block:
    - name: Copy other cert
      copy:
        src: "{{ other_cert }}"
        dest: "/tmp/other-cert-ansible-managed.crt"
        mode: '400'
        setype: cert_t
      changed_when: false

    # -t "C,," is probably good enough, P makes more sense but maybe it has been
    # removed or existed only in some weird version of certutil, since it seems
    # to be ignored
    - name: Install other certificate into NSS db
      command: >
        certutil -A
        -d '/etc/dirsrv/slapd-default'
        -n '{{ other_cert | basename | replace('.', '_') }}-ansible-managed'
        -t 'PC,PC,PC'
        -i '/tmp/other-cert-ansible-managed.crt'
      changed_when: false

    # Detecting when something changed is too complicated
    - name: Restart 389DS
      service:
        name: "dirsrv@{{ dirsrv_serverid }}"
        state: restarted

    always:
    - name: Remove temporary files
      file:
        state: absent
        path: "/tmp/other-cert-ansible-managed.crt"
      changed_when: false

  - name: Ensure container entries exist
    ldap_entry:
      server_uri: "ldap://localhost"
      validate_certs: "false"
      start_tls: "true"
      bind_dn: "cn=Directory Manager"
      bind_pw: "{{ dirsrv_rootdn_password }}"
      dn: "{{ item.dn }}"
      objectClass: "{{ item.objectClass }}"
      state: "{{ 'present' if item.present else 'absent' }}"
    loop:
      - { dn: "ou=Groups,dc=example,dc=local", objectClass: ["organizationalunit", "top"], present: true }
      - { dn: "ou=People,dc=example,dc=local", objectClass: ["organizationalunit", "top"], present: true }
      - { dn: "ou=Services,dc=example,dc=local", objectClass: ["organizationalunit", "top"], present: true }
      - { dn: "ou=Special Users,dc=example,dc=local", objectClass: ["organizationalunit", "top"], present: false }
      - { dn: "ou=Directory Managers,dc=example,dc=local", objectClass: ["organizationalunit", "top"], present: false }

  - name: Configure ACIs
    ldap_attr:
      server_uri: "ldap://localhost"
      validate_certs: "false"
      start_tls: "true"
      bind_dn: "cn=Directory Manager"
      bind_pw: "{{ dirsrv_rootdn_password }}"
      dn: "{{ item.dn }}"
      state: exact
      name: "aci"
      values: "{{ item.acis }}"
    loop:
      -
        dn: "{{ dirsrv_suffix }}"
        acis:
          - '(target = "ldap:///{{ dirsrv_suffix }}")(targetattr = "objectClass") (version 3.0; acl "Allow all to read suffix"; allow (search, read) userdn = "ldap:///all";)'
      -
        dn: "ou=People,{{ dirsrv_suffix }}"
        acis:
          - '(targetfilter = "(uid=*)")(targetattr = "objectClass || memberOf || dn || cn || uid || telegramID || createTimestamp || creatorsName || entrydn || entryid || hasSubordinates || modifiersName || modifyTimestamp || nsUniqueId || numSubordinates || parentid || subschemaSubentry") (version 3.0; acl "Allow Keycloak to read users"; allow (search, read, compare) userdn = "ldap:///cn=Keycloak,ou=Services,{{ dirsrv_suffix }}";)'
          - '(targetfilter = "(uid=*)")(targetattr = "userPassword") (version 3.0; acl "Allow Keycloak to change passwords"; allow (write) userdn = "ldap:///cn=Keycloak,ou=Services,{{ dirsrv_suffix }}";)'
          - '(targetfilter = "(uid=*)")(targetattr = "userPassword") (version 3.0; acl "Allow users to change their password"; allow (write) userdn = "ldap:///self";)'
          - '(targetfilter = "(uid=*)")(targetattr = "createTimestamp || creatorsName || modifiersName || modifyTimestamp || objectClass || memberOf || uid || sn || schacPersonalUniqueCode || degreeCourse || schacDateOfBirth || schacPlaceOfBirth || mobile || mail || safetyTestDate || telegramID || telegramNickname || description") (version 3.0; acl "Allow HR to read users"; allow (search, read, compare) groupdn = "ldap:///cn=HR,ou=Groups,{{ dirsrv_suffix }}";)'
          - '(targetfilter="(&(uid=*)(objectClass=top)(objectClass=inetOrgPerson)(objectClass=organizationalPerson)(objectClass=person)(objectClass=schacPersonalCharacteristics)(objectClass=telegramAccount)(objectClass=weeeOpenPerson))")(targetattr = "objectClass ||  uid || sn || schacPersonalUniqueCode || degreeCourse || schacDateOfBirth || schacPlaceOfBirth || mobile || mail || safetyTestDate || telegramID || telegramNickname || description") (version 3.0; acl "Allow HR to add, edit, delete users"; allow (write, add, delete) groupdn = "ldap:///cn=HR,ou=Groups,{{ dirsrv_suffix }}";)'
          - '(targetfilter = "(uid=*)")(targetattr = "userPassword") (version 3.0; acl "Allow HR to change users password"; allow (write, add) groupdn = "ldap:///cn=HR,ou=Groups,{{ dirsrv_suffix }}";)'
      -
        dn: "ou=Groups,{{ dirsrv_suffix }}"
        acis:
          - '(targetfilter = "(cn=*)")(targetattr = "objectClass || cn || ou || description || member || uniqueMember  || createTimestamp || creatorsName || entrydn || entryid || hasSubordinates || modifiersName || modifyTimestamp || nsUniqueId || numSubordinates || parentid || subschemaSubentry") (version 3.0; acl "Allow Keycloak to read groups"; allow (search, read, compare) userdn = "ldap:///cn=Keycloak,ou=Services,{{ dirsrv_suffix }}";)'
          - '(targetfilter = "(cn=*)")(targetattr = "objectClass || cn || ou || description || member || uniqueMember") (version 3.0; acl "Allow HR to read groups"; allow (search, read, compare) groupdn = "ldap:///cn=HR,ou=Groups,{{ dirsrv_suffix }}";)'
          - '(targetfilter = "(cn=*)")(targetattr = "member || uniqueMember") (version 3.0; acl "Allow HR to add and remove people from groups"; allow (write) groupdn = "ldap:///cn=HR,ou=Groups,{{ dirsrv_suffix }}";)'
    tags: acis

  - name: Configure password policy
    ldap_attr:
      server_uri: "ldap://localhost"
      validate_certs: "false"
      start_tls: "true"
      bind_dn: "cn=Directory Manager"
      bind_pw: "{{ dirsrv_rootdn_password }}"
      dn: "cn=config"
      state: exact
      name: "{{ item.name }}"
      values: "{{ item.value }}"
    loop:
      - { name: "passwordCheckSyntax", value: "on" }
      - { name: "passwordMinLength", value: "16" }
      # "password minimum number of categories "0" is invalid. The minimum number of categories must range from 1 to 5."
      # And the reference says the minimum is 0...
      - { name: "passwordMinCategories", value: "1" }
      - { name: "passwordLockout", value: "on" }
      - { name: "passwordMaxFailure", value: "6" }
      - { name: "passwordLockoutDuration", value: "120" }
      - { name: "passwordLegacyPolicy", value: "off" }
      - { name: "passwordIsGlobalPolicy", value: "on" }
    tags: acis
