---
- hosts: wso2
  become: true

  vars:
    dirsrv_suffix: dc=sso,dc=local

    wso2is_admin: wso2admin
    wso2is_admin_password: asd
    wso2is_hostname: "{{ ansible_fqdn }}"
    wso2is_ldap_url: "ldap://ldap1.sso.local:389" # TODO: ldaps
    wso2is_version: "5.7.0"
    wso2is_account: "cn=WSO2IS,ou=Services,{{ dirsrv_suffix }}"
    wso2is_account_password: "asd"
    wso2is_people_base: "ou=People,{{ dirsrv_suffix }}"
    wso2is_user_entry_object_class: "weeeOpenPerson"
    wso2is_user_dn_pattern: "uid={0},ou=People,{{ dirsrv_suffix }}"
    wso2is_groups_base: "ou=Groups,{{ dirsrv_suffix }}"
    wso2is_groups_dn_pattern: "uid={0},ou=Groups,{{ dirsrv_suffix }}"

  pre_tasks:
  - name: Set hosts file
    copy: src=hosts dest=/etc/hosts owner=root group=root

  tasks:
  - name: Install OpenJDK 8
    yum:
      name: java-1.8.0-openjdk-headless
      state: present
    become: true

  - name: Add WSO2 repo
    get_url:
      url: "https://bintray.com/wso2/rpm/rpm"
      dest: "/etc/yum.repos.d/bintray-wso2-rpm.repo"
      owner: root
      group: root
    become: true

  - name: Install WSO2 Identity Server
    yum:
      name: wso2is-{{ wso2is_version }}
      state: present
    become: true

  - name: Create WSO2 group
    group:
      name: wso2
      system: true
      gid: 802
    become: true

  - name: Add WSO2 user
    user:
      name: wso2
      group: wso2
      uid: 802
      shell: /sbin/nologin
    become: true

  - name: Change the owner of WSO2 directory
    file:
      path: "/usr/lib64/wso2/wso2is/{{ wso2is_version }}"
      state: directory
      recurse: true
      owner: wso2
      group: wso2
      mode: 0755
    become: true

  - name: Deploy user-mgt.xml
    template:
      src: wso2/user-mgt.xml.j2
      dest: "/usr/lib64/wso2/wso2is/{{ wso2is_version }}/repository/conf/user-mgt.xml"
      owner: wso2
      group: wso2
      mode: 0440
    become: true
    notify: restart WSO2IS

  - name: Deploy carbon.xml
    template:
      src: wso2/carbon.xml.j2
      dest: "/usr/lib64/wso2/wso2is/{{ wso2is_version }}/repository/conf/carbon.xml"
      owner: wso2
      group: wso2
      mode: 0440
    become: true
    notify: restart WSO2IS

  - name: Disable embedded LDAP
    copy:
      src: wso2/embedded-ldap.xml
      dest: "/usr/lib64/wso2/wso2is/{{ wso2is_version }}/repository/conf/identity/embedded-ldap.xml"
      owner: wso2
      group: wso2
      mode: 0440
    become: true
    notify: restart WSO2IS

  - name: Copy WSO2IS service file
    template:
      src: "wso2/wso2is.service.j2"
      dest: /etc/systemd/system/wso2is.service
    become: true
    register: wso2is_service

  - name: "Reload systemctl daemon"
    command: systemctl daemon-reload
    become: true
    when: wso2is_service.changed

  - name: "Start wso2-is as a service"
    service:
      name: wso2is
      state: started
      enabled: true
    become: true

  handlers:
  - name: restart WSO2IS
    service:
      name: wso2is
      state: restarted
    become: true
